using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace TaskManager.Models;

public class AssignedTask
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }

    [BsonRepresentation(BsonType.ObjectId)]
    public string UserId { get; set; }

    [BsonRepresentation(BsonType.ObjectId)]
    public string TaskId { get; set; } // Reference to main task model

    [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
    public DateTime TaskDate { get; set; } // Specific date it was assigned for

    public string Title { get; set; }

    public string Description { get; set; }

    [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
    public DateTime StartTime { get; set; }  // 10:00 PM

    [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
    public DateTime EndTime { get; set; }    // 12:00 AM

    public int ExpectedDurationMinutes => (int)(EndTime - StartTime).TotalMinutes;

    public string Status { get; set; } = "Pending"; // Pending, Completed, Skipped

    public bool AutoGenerated { get; set; } = true;

    [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
