// Progress Dashboard Action Types

// User Stats
export const SET_USER_STATS = "SET_USER_STATS";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

// Leaderboard
export const SET_WEEKLY_LEADERBOARD = "SET_WEEKLY_LEADERBOARD";
export const SET_MONTHLY_LEADERBOARD = "SET_MONTHLY_LEADERBOARD";

// Category Stats
export const SET_CATEGORY_STATS = "SET_CATEGORY_STATS";

// Tab Management
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";

// Loading States for async operations
export const FETCH_USER_STATS_START = "FETCH_USER_STATS_START";
export const FETCH_USER_STATS_SUCCESS = "FETCH_USER_STATS_SUCCESS";
export const FETCH_USER_STATS_ERROR = "FETCH_USER_STATS_ERROR";

export const FETCH_LEADERBOARD_START = "FETCH_LEADERBOARD_START";
export const FETCH_LEADERBOARD_SUCCESS = "FETCH_LEADERBOARD_SUCCESS";
export const FETCH_LEADERBOARD_ERROR = "FETCH_LEADERBOARD_ERROR";

export const FETCH_CATEGORY_STATS_START = "FETCH_CATEGORY_STATS_START";
export const FETCH_CATEGORY_STATS_SUCCESS = "FETCH_CATEGORY_STATS_SUCCESS";
export const FETCH_CATEGORY_STATS_ERROR = "FETCH_CATEGORY_STATS_ERROR";

export const FETCH_ALL_DATA_START = "FETCH_ALL_DATA_START";
export const FETCH_ALL_DATA_SUCCESS = "FETCH_ALL_DATA_SUCCESS";
export const FETCH_ALL_DATA_ERROR = "FETCH_ALL_DATA_ERROR";
