// Task Management Action Types
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_ALL_TASKS = "SET_ALL_TASKS";
export const SET_CALENDAR_TASKS = "SET_CALENDAR_TASKS";
export const SET_ACTIVE_VIEW = "SET_ACTIVE_VIEW";
export const SET_SELECTED_TASK = "SET_SELECTED_TASK";
export const SET_MODAL_VISIBLE = "SET_MODAL_VISIBLE";
export const SET_ADD_TASK_OPEN = "SET_ADD_TASK_OPEN";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

// Loading states
export const FETCH_TASKS_START = "FETCH_TASKS_START";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_ERROR = "FETCH_TASKS_ERROR";

export const FETCH_CALENDAR_TASKS_START = "FETCH_CALENDAR_TASKS_START";
export const FETCH_CALENDAR_TASKS_SUCCESS = "FETCH_CALENDAR_TASKS_SUCCESS";
export const FETCH_CALENDAR_TASKS_ERROR = "FETCH_CALENDAR_TASKS_ERROR";

// Delete task action types
export const DELETE_TASK_START = "DELETE_TASK_START";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";
